// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPBC94CP74ib3gahfnmj0bjTUsmbm-2DA',
    appId: '1:867429470268:web:ee4e6ad4330cd69053f339',
    messagingSenderId: '867429470268',
    projectId: 'uni-talk-81f81',
    authDomain: 'uni-talk-81f81.firebaseapp.com',
    storageBucket: 'uni-talk-81f81.appspot.com',
    measurementId: 'G-FRW23ZMWW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC815rmVjqOEa4mUCMjcWnM2XDCjnPkn1o',
    appId: '1:867429470268:android:2fa73a0028ec063053f339',
    messagingSenderId: '867429470268',
    projectId: 'uni-talk-81f81',
    storageBucket: 'uni-talk-81f81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeuG9SmiPRXZM-IcQuAf8sxVPAUjLp24A',
    appId: '1:867429470268:ios:a040459bef6bd77a53f339',
    messagingSenderId: '867429470268',
    projectId: 'uni-talk-81f81',
    storageBucket: 'uni-talk-81f81.appspot.com',
    iosClientId: '867429470268-h14aiqbqu3mbscdb995640ndt6mffd8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeuG9SmiPRXZM-IcQuAf8sxVPAUjLp24A',
    appId: '1:867429470268:ios:a040459bef6bd77a53f339',
    messagingSenderId: '867429470268',
    projectId: 'uni-talk-81f81',
    storageBucket: 'uni-talk-81f81.appspot.com',
    iosClientId: '867429470268-h14aiqbqu3mbscdb995640ndt6mffd8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniTalk',
  );
}
